# Generated by Django 4.0 on 2021-12-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_view',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
